### ISSUE TITLE
Relearn how to use this as burn-in plugin

### ISSUE THREAD

**Issue by CoffeeIntoScience** [ypsun-umd/labSNMP#1]
I've checked this out and re-learned how to talk to the MARATON with it

In addition to controlling channels on and off, I've found a page that specifies the bizzare return values when trying to read the sensed current or voltage 

```
 Float ::= TEXTUAL-CONVENTION
    STATUS      current
    DESCRIPTION
        "A single precision floating-point number.  The semantics
         and encoding are identical for type 'single' defined in
         IEEE Standard for Binary Floating-Point,
         ANSI/IEEE Std 754-1985.
         The value is restricted to the BER serialization of
         the following ASN.1 type:
             FLOATTYPE ::= [120] IMPLICIT FloatType
         (note: the value 120 is the sum of '30'h and '48'h)
         The BER serialization of the length for values of
         this type must use the definite length, short
         encoding form.

         For example, the BER serialization of value 123
         of type FLOATTYPE is '9f780442f60000'h.  (The tag
         is '9f78'h; the length is '04'h; and the value is
         '42f60000'h.) The BER serialization of value
         '9f780442f60000'h of data type Opaque is
         '44079f780442f60000'h. (The tag is '44'h; the length
         is '07'h; and the value is '9f780442f60000'h."
    SYNTAX Opaque (SIZE (7))

```

knowing and knowing the MARATON basically always uses 0x9f7804 as the prefix, I've written:

```
def ConvertFloat(num):
    num=num & 0xFFFFFFFF
    sign=num >> 31
    num=num & 0x7FFFFFFF
    exponent=num >> 23
    exponent+=-127
    fraction=0
    for x in range(1,23,1):
        fraction+=(num & (1 << (23-x)) > 0) * pow(2,-x)
    return ((1+fraction)*pow(2,exponent)*(1-2*sign))
```
and am getting values that agree with the usb control

**Comment by CoffeeIntoScience** [comment]
Simple usage (since it's not transparently documented) is like

`python3 power-supply-ctrl.py -t 169.254.0.1 -m wiener get u1 current`

or

`python3 power-supply-ctrl.py -t 169.254.0.1 -m wiener set u1 off`

**Comment by CoffeeIntoScience** [comment]
(assignees should probably actually have been mentions. sorry. I'm bad at git)

**Comment by yipengsun** [comment]
I kinda forgot the utility of the files located under `labSNMP/compiled` since they are not imported anywhere. My guess is that these are not really needed once we decipher the control interface for our PSUs, which we/I did.

I think currently, all operations are done synchronously, which makes it harder to integrate with our "remote" control system. I probably need to write some additional code for that. 

Last time I checked (~summer 2018), I think the underlying library (`pysnmp`) can already do network operations asynchronously, so it shouldn't be too hard. I'm going to focus on this in the next 2 to 3 days. 

BTW, have we set up the LAN in the basement with the ubnt router (that one can configure a static DHCP IP address for specific devices, making the remote control reliable since we will have a guaranteed IP address for them).

**Comment by CoffeeIntoScience** [comment]
Documentation seems to say you should work with it using the asyncore module

```
pysnmp.hlapi.asyncore.setCmd(snmpEngine, authData, transportTarget,contextData,*varBinds,**options)
```
as compared to
```
pysnmp.hlapi.setCmd(snmpEngine, authData, transportTarget, contextData, *varBinds, **options)
```

so at first glance they look like a direct drop-in replacement

**Comment by CoffeeIntoScience** [comment]
LAN is up in the air still. We've been escalated even higher. Waiting on IT to make an actual decision of any kind :P

**Comment by CoffeeIntoScience** [comment]
If we get declined, the other interesting option is to set up a Rpi with static IP and 2nd NIC which goes to a dumb hub that's the pi+MARATON+whatever
